# Generated by Django 5.0 on 2024-01-05 04:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('study', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_path', models.FileField(upload_to='audios/')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiofile', to=settings.AUTH_USER_MODEL)),
                ('ko_text', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audiofile', to='study.sentence')),
            ],
        ),
    ]
