# Generated by Django 4.2.9 on 2024-01-05 07:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("study", "0002_audiofile"),
    ]

    operations = [
        migrations.RenameField(
            model_name="audiofile",
            old_name="ko_text",
            new_name="sentence",
        ),
        migrations.RenameField(
            model_name="bookmark",
            old_name="ko_text",
            new_name="sentence",
        ),
        migrations.RenameField(
            model_name="result",
            old_name="ko_text",
            new_name="sentence",
        ),
    ]
