# Generated by Django 5.0 on 2023-12-28 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='genre_preferences',
        ),
        migrations.RemoveField(
            model_name='user',
            name='singer_preferences',
        ),
        migrations.AddField(
            model_name='user',
            name='selectedArtist',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='selectedGenres',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
