# Generated by Django 5.0 on 2024-01-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('introduce', '0002_comment_post_delete_notice_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
